package yxinfo.core.service.ou.dao.model;

public class EnterpriseManager {
    //企业/学校id，<FK>enterprise_core.id
    private Integer enterpriseId;

    //用户id，<FK>sys_member.id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_manager.enterprise_id
     *
     * @return the value of enterprise_manager.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_manager.enterprise_id
     *
     * @param enterpriseId the value for enterprise_manager.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_manager.member_id
     *
     * @return the value of enterprise_manager.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_manager.member_id
     *
     * @param memberId the value for enterprise_manager.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}