package yxinfo.core.service.ou.dao.model;

public class SysApp {
    //应用编号
    private String app;

    //名称
    private String fname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app.app
     *
     * @return the value of sys_app.app
     *
     * @mbggenerated
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app.app
     *
     * @param app the value for sys_app.app
     *
     * @mbggenerated
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app.fname
     *
     * @return the value of sys_app.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app.fname
     *
     * @param fname the value for sys_app.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }
}