package yxinfo.core.service.ou.dao.model;

public class SysAppTerminal {
    //应用编号，<FK>sys_app.app
    private String app;

    //终端编号，<FK>sys_terminal.term_code
    private String termCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_terminal.app
     *
     * @return the value of sys_app_terminal.app
     *
     * @mbggenerated
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_terminal.app
     *
     * @param app the value for sys_app_terminal.app
     *
     * @mbggenerated
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_app_terminal.term_code
     *
     * @return the value of sys_app_terminal.term_code
     *
     * @mbggenerated
     */
    public String getTermCode() {
        return termCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_app_terminal.term_code
     *
     * @param termCode the value for sys_app_terminal.term_code
     *
     * @mbggenerated
     */
    public void setTermCode(String termCode) {
        this.termCode = termCode == null ? null : termCode.trim();
    }
}