package yxinfo.core.service.ou.dao.model;

import java.util.Date;

public class SysAccessTok {
    //访问令牌
    private String accessTok;

    //终端编号（terminal），<FK>sys_terminal.terminal
    private String deviceType;

    //创建时间
    private Date createAt;

    //用户id，<FK>sys_member.id
    private Integer memberId;

    //终端设备品牌，2.0移除
    private String deviceBrand;

    //终端设备型号，2.0移除
    private String deviceModel;

    //设备唯一标识，2.0移除
    private String imei;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.access_tok
     *
     * @return the value of sys_access_tok.access_tok
     *
     * @mbggenerated
     */
    public String getAccessTok() {
        return accessTok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.access_tok
     *
     * @param accessTok the value for sys_access_tok.access_tok
     *
     * @mbggenerated
     */
    public void setAccessTok(String accessTok) {
        this.accessTok = accessTok == null ? null : accessTok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.device_type
     *
     * @return the value of sys_access_tok.device_type
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.device_type
     *
     * @param deviceType the value for sys_access_tok.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.create_at
     *
     * @return the value of sys_access_tok.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.create_at
     *
     * @param createAt the value for sys_access_tok.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.member_id
     *
     * @return the value of sys_access_tok.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.member_id
     *
     * @param memberId the value for sys_access_tok.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.device_brand
     *
     * @return the value of sys_access_tok.device_brand
     *
     * @mbggenerated
     */
    public String getDeviceBrand() {
        return deviceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.device_brand
     *
     * @param deviceBrand the value for sys_access_tok.device_brand
     *
     * @mbggenerated
     */
    public void setDeviceBrand(String deviceBrand) {
        this.deviceBrand = deviceBrand == null ? null : deviceBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.device_model
     *
     * @return the value of sys_access_tok.device_model
     *
     * @mbggenerated
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.device_model
     *
     * @param deviceModel the value for sys_access_tok.device_model
     *
     * @mbggenerated
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.imei
     *
     * @return the value of sys_access_tok.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.imei
     *
     * @param imei the value for sys_access_tok.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }
}