package yxinfo.core.service.ou.dao.model;

public class SysIp {
    //ip地址
    private String ip;

    //国家
    private String country;

    //省
    private String province;

    //市
    private String city;

    //区
    private String district;

    //网络
    private String isp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.ip
     *
     * @return the value of sys_ip.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.ip
     *
     * @param ip the value for sys_ip.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.country
     *
     * @return the value of sys_ip.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.country
     *
     * @param country the value for sys_ip.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.province
     *
     * @return the value of sys_ip.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.province
     *
     * @param province the value for sys_ip.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.city
     *
     * @return the value of sys_ip.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.city
     *
     * @param city the value for sys_ip.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.district
     *
     * @return the value of sys_ip.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.district
     *
     * @param district the value for sys_ip.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ip.isp
     *
     * @return the value of sys_ip.isp
     *
     * @mbggenerated
     */
    public String getIsp() {
        return isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ip.isp
     *
     * @param isp the value for sys_ip.isp
     *
     * @mbggenerated
     */
    public void setIsp(String isp) {
        this.isp = isp == null ? null : isp.trim();
    }
}