package yxinfo.core.service.ou.dao.model;

import java.util.Date;

public class SysLoginInfo {
    //用户id，<FK>sys_member.id
    private Integer memberId;

    //终端编号（terminal），<FK>sys_terminal.term_code
    private String termCode;

    //设备品牌
    private String deviceBrand;

    //设备型号
    private String deviceModel;

    //设备唯一标识
    private String imei;

    //系统版本号
    private String systemVer;

    //是否采用默认App推送渠道
    private Boolean defAppPush;

    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.member_id
     *
     * @return the value of sys_login_info.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.member_id
     *
     * @param memberId the value for sys_login_info.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.term_code
     *
     * @return the value of sys_login_info.term_code
     *
     * @mbggenerated
     */
    public String getTermCode() {
        return termCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.term_code
     *
     * @param termCode the value for sys_login_info.term_code
     *
     * @mbggenerated
     */
    public void setTermCode(String termCode) {
        this.termCode = termCode == null ? null : termCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.device_brand
     *
     * @return the value of sys_login_info.device_brand
     *
     * @mbggenerated
     */
    public String getDeviceBrand() {
        return deviceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.device_brand
     *
     * @param deviceBrand the value for sys_login_info.device_brand
     *
     * @mbggenerated
     */
    public void setDeviceBrand(String deviceBrand) {
        this.deviceBrand = deviceBrand == null ? null : deviceBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.device_model
     *
     * @return the value of sys_login_info.device_model
     *
     * @mbggenerated
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.device_model
     *
     * @param deviceModel the value for sys_login_info.device_model
     *
     * @mbggenerated
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.imei
     *
     * @return the value of sys_login_info.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.imei
     *
     * @param imei the value for sys_login_info.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.system_ver
     *
     * @return the value of sys_login_info.system_ver
     *
     * @mbggenerated
     */
    public String getSystemVer() {
        return systemVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.system_ver
     *
     * @param systemVer the value for sys_login_info.system_ver
     *
     * @mbggenerated
     */
    public void setSystemVer(String systemVer) {
        this.systemVer = systemVer == null ? null : systemVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.def_app_push
     *
     * @return the value of sys_login_info.def_app_push
     *
     * @mbggenerated
     */
    public Boolean getDefAppPush() {
        return defAppPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.def_app_push
     *
     * @param defAppPush the value for sys_login_info.def_app_push
     *
     * @mbggenerated
     */
    public void setDefAppPush(Boolean defAppPush) {
        this.defAppPush = defAppPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_info.create_at
     *
     * @return the value of sys_login_info.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_info.create_at
     *
     * @param createAt the value for sys_login_info.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}