package yxinfo.core.service.ou.dao.model;

public class SysLoginRegionNum {
    //用户id，<FK>sys_member.id
    private Integer memberId;

    //终端类型编号
    private String region;

    //次数
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_region_num.member_id
     *
     * @return the value of sys_login_region_num.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_region_num.member_id
     *
     * @param memberId the value for sys_login_region_num.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_region_num.region
     *
     * @return the value of sys_login_region_num.region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_region_num.region
     *
     * @param region the value for sys_login_region_num.region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_region_num.num
     *
     * @return the value of sys_login_region_num.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_region_num.num
     *
     * @param num the value for sys_login_region_num.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}