package yxinfo.core.service.ou.dao.model;

public class SysMemberOrg {
    private Integer id;

    //成员id
    private Integer memberId;

    //组织id
    private Integer orgId;

    //人员编号
    private String fcode;

    //职位
    private String position;

    //认证状态（1未认证，2已认证）
    private Short authStatus;

    //座机
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.id
     *
     * @return the value of sys_member_org.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.id
     *
     * @param id the value for sys_member_org.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.member_id
     *
     * @return the value of sys_member_org.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.member_id
     *
     * @param memberId the value for sys_member_org.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.org_id
     *
     * @return the value of sys_member_org.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.org_id
     *
     * @param orgId the value for sys_member_org.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.fcode
     *
     * @return the value of sys_member_org.fcode
     *
     * @mbggenerated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.fcode
     *
     * @param fcode the value for sys_member_org.fcode
     *
     * @mbggenerated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.position
     *
     * @return the value of sys_member_org.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.position
     *
     * @param position the value for sys_member_org.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.auth_status
     *
     * @return the value of sys_member_org.auth_status
     *
     * @mbggenerated
     */
    public Short getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.auth_status
     *
     * @param authStatus the value for sys_member_org.auth_status
     *
     * @mbggenerated
     */
    public void setAuthStatus(Short authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org.tel
     *
     * @return the value of sys_member_org.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org.tel
     *
     * @param tel the value for sys_member_org.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}