package yxinfo.core.service.ou.dao.model;

public class SysMenu {
    private Integer id;

    //名称
    private String fname;

    //上级菜单id，<FK>sys_menu.id
    private Integer pid;

    //所属功能模块id，<FK>sys_mod.id
    private Integer modId;

    //图标
    private String icon;

    //路由
    private String ref;

    //标签
    private String tab;

    //副路由
    private String srefActive;

    //终端编号（terminal），<FK>sys_terminal.term_code
    private String termCode;

    //应用编号，<FK>sys_app.app
    private String app;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.fname
     *
     * @return the value of sys_menu.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.fname
     *
     * @param fname the value for sys_menu.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.pid
     *
     * @return the value of sys_menu.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.pid
     *
     * @param pid the value for sys_menu.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.mod_id
     *
     * @return the value of sys_menu.mod_id
     *
     * @mbggenerated
     */
    public Integer getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.mod_id
     *
     * @param modId the value for sys_menu.mod_id
     *
     * @mbggenerated
     */
    public void setModId(Integer modId) {
        this.modId = modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.icon
     *
     * @return the value of sys_menu.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.icon
     *
     * @param icon the value for sys_menu.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.ref
     *
     * @return the value of sys_menu.ref
     *
     * @mbggenerated
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.ref
     *
     * @param ref the value for sys_menu.ref
     *
     * @mbggenerated
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.tab
     *
     * @return the value of sys_menu.tab
     *
     * @mbggenerated
     */
    public String getTab() {
        return tab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.tab
     *
     * @param tab the value for sys_menu.tab
     *
     * @mbggenerated
     */
    public void setTab(String tab) {
        this.tab = tab == null ? null : tab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sref_active
     *
     * @return the value of sys_menu.sref_active
     *
     * @mbggenerated
     */
    public String getSrefActive() {
        return srefActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sref_active
     *
     * @param srefActive the value for sys_menu.sref_active
     *
     * @mbggenerated
     */
    public void setSrefActive(String srefActive) {
        this.srefActive = srefActive == null ? null : srefActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.term_code
     *
     * @return the value of sys_menu.term_code
     *
     * @mbggenerated
     */
    public String getTermCode() {
        return termCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.term_code
     *
     * @param termCode the value for sys_menu.term_code
     *
     * @mbggenerated
     */
    public void setTermCode(String termCode) {
        this.termCode = termCode == null ? null : termCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.app
     *
     * @return the value of sys_menu.app
     *
     * @mbggenerated
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.app
     *
     * @param app the value for sys_menu.app
     *
     * @mbggenerated
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }
}