package yxinfo.core.service.ou.dao.model;

import java.util.Date;

public class SysMember {
    private Integer id;

    //登录名
    private String loginName;

    //密码
    private String pwd;

    //姓名
    private String realName;

    //姓名拼音
    private String pyinName;

    //昵称
    private String nickName;

    //手机号
    private String mobile;

    //头像
    private Integer head;

    private Date createAt;

    private Date updateAt;

    //是否被删除（1是，0否）
    private Boolean isDel;

    //密码错误次数
    private Integer pwdErrcount;

    //上一次密码错误时间
    private Date pwdErrAt;

    //性别（0无记录，1男，2女）
    private Short sex;

    //排序权重
    private Integer sort;

    //人员类型（1个人，2企业）
    private Short ftype;

    //邮箱
    private String email;

    //部门名称
    private String departName;

    //企业/学校名称
    private String enterpriseName;

    //学校id
    private Integer enterpriseId;

    //企业类型（）
    private Short enterpriseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.id
     *
     * @return the value of sys_member.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.id
     *
     * @param id the value for sys_member.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.login_name
     *
     * @return the value of sys_member.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.login_name
     *
     * @param loginName the value for sys_member.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.pwd
     *
     * @return the value of sys_member.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.pwd
     *
     * @param pwd the value for sys_member.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.real_name
     *
     * @return the value of sys_member.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.real_name
     *
     * @param realName the value for sys_member.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.pyin_name
     *
     * @return the value of sys_member.pyin_name
     *
     * @mbg.generated
     */
    public String getPyinName() {
        return pyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.pyin_name
     *
     * @param pyinName the value for sys_member.pyin_name
     *
     * @mbg.generated
     */
    public void setPyinName(String pyinName) {
        this.pyinName = pyinName == null ? null : pyinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.nick_name
     *
     * @return the value of sys_member.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.nick_name
     *
     * @param nickName the value for sys_member.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.mobile
     *
     * @return the value of sys_member.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.mobile
     *
     * @param mobile the value for sys_member.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.head
     *
     * @return the value of sys_member.head
     *
     * @mbg.generated
     */
    public Integer getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.head
     *
     * @param head the value for sys_member.head
     *
     * @mbg.generated
     */
    public void setHead(Integer head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.create_at
     *
     * @return the value of sys_member.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.create_at
     *
     * @param createAt the value for sys_member.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.update_at
     *
     * @return the value of sys_member.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.update_at
     *
     * @param updateAt the value for sys_member.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.is_del
     *
     * @return the value of sys_member.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.is_del
     *
     * @param isDel the value for sys_member.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.pwd_errcount
     *
     * @return the value of sys_member.pwd_errcount
     *
     * @mbg.generated
     */
    public Integer getPwdErrcount() {
        return pwdErrcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.pwd_errcount
     *
     * @param pwdErrcount the value for sys_member.pwd_errcount
     *
     * @mbg.generated
     */
    public void setPwdErrcount(Integer pwdErrcount) {
        this.pwdErrcount = pwdErrcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.pwd_err_at
     *
     * @return the value of sys_member.pwd_err_at
     *
     * @mbg.generated
     */
    public Date getPwdErrAt() {
        return pwdErrAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.pwd_err_at
     *
     * @param pwdErrAt the value for sys_member.pwd_err_at
     *
     * @mbg.generated
     */
    public void setPwdErrAt(Date pwdErrAt) {
        this.pwdErrAt = pwdErrAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.sex
     *
     * @return the value of sys_member.sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.sex
     *
     * @param sex the value for sys_member.sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.sort
     *
     * @return the value of sys_member.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.sort
     *
     * @param sort the value for sys_member.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.ftype
     *
     * @return the value of sys_member.ftype
     *
     * @mbg.generated
     */
    public Short getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.ftype
     *
     * @param ftype the value for sys_member.ftype
     *
     * @mbg.generated
     */
    public void setFtype(Short ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.email
     *
     * @return the value of sys_member.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.email
     *
     * @param email the value for sys_member.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.depart_name
     *
     * @return the value of sys_member.depart_name
     *
     * @mbg.generated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.depart_name
     *
     * @param departName the value for sys_member.depart_name
     *
     * @mbg.generated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.enterprise_name
     *
     * @return the value of sys_member.enterprise_name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.enterprise_name
     *
     * @param enterpriseName the value for sys_member.enterprise_name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.enterprise_id
     *
     * @return the value of sys_member.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.enterprise_id
     *
     * @param enterpriseId the value for sys_member.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.enterprise_type
     *
     * @return the value of sys_member.enterprise_type
     *
     * @mbg.generated
     */
    public Short getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.enterprise_type
     *
     * @param enterpriseType the value for sys_member.enterprise_type
     *
     * @mbg.generated
     */
    public void setEnterpriseType(Short enterpriseType) {
        this.enterpriseType = enterpriseType;
    }
}