package yxinfo.core.service.sms.dao.model;

import java.util.Date;

public class EvtSmsRecord {
    private Integer id;

    private Integer orgid;

    //类型（1普通，2营销）
    private String ftype;

    //发送数目
    private Short num;

    //接收号码
    private String mobiles;

    //内容
    private String content;

    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.id
     *
     * @return the value of evt_sms_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.id
     *
     * @param id the value for evt_sms_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.orgId
     *
     * @return the value of evt_sms_record.orgId
     *
     * @mbggenerated
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.orgId
     *
     * @param orgid the value for evt_sms_record.orgId
     *
     * @mbggenerated
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.ftype
     *
     * @return the value of evt_sms_record.ftype
     *
     * @mbggenerated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.ftype
     *
     * @param ftype the value for evt_sms_record.ftype
     *
     * @mbggenerated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.num
     *
     * @return the value of evt_sms_record.num
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.num
     *
     * @param num the value for evt_sms_record.num
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.mobiles
     *
     * @return the value of evt_sms_record.mobiles
     *
     * @mbggenerated
     */
    public String getMobiles() {
        return mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.mobiles
     *
     * @param mobiles the value for evt_sms_record.mobiles
     *
     * @mbggenerated
     */
    public void setMobiles(String mobiles) {
        this.mobiles = mobiles == null ? null : mobiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.content
     *
     * @return the value of evt_sms_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.content
     *
     * @param content the value for evt_sms_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_sms_record.create_at
     *
     * @return the value of evt_sms_record.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_sms_record.create_at
     *
     * @param createAt the value for evt_sms_record.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}