package yxinfo.core.service.sms.dao.model;

import java.util.Date;

public class EvtVcodeNum {
    //手机号
    private String mobile;

    //发送次数
    private Integer num;

    //标记时间
    private Date flagAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode_num.mobile
     *
     * @return the value of evt_vcode_num.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode_num.mobile
     *
     * @param mobile the value for evt_vcode_num.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode_num.num
     *
     * @return the value of evt_vcode_num.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode_num.num
     *
     * @param num the value for evt_vcode_num.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode_num.flag_at
     *
     * @return the value of evt_vcode_num.flag_at
     *
     * @mbggenerated
     */
    public Date getFlagAt() {
        return flagAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode_num.flag_at
     *
     * @param flagAt the value for evt_vcode_num.flag_at
     *
     * @mbggenerated
     */
    public void setFlagAt(Date flagAt) {
        this.flagAt = flagAt;
    }
}