package yxinfo.core.service.sms.dao.model;

import java.util.Date;

public class EvtVcode {
    private Integer id;

    //用于的功能码
    private String useAt;

    //验证码
    private String fcode;

    //手机号
    private String mobile;

    //创建时间
    private Date createAt;

    //验证错误次数
    private Integer errCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.id
     *
     * @return the value of evt_vcode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.id
     *
     * @param id the value for evt_vcode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.use_at
     *
     * @return the value of evt_vcode.use_at
     *
     * @mbggenerated
     */
    public String getUseAt() {
        return useAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.use_at
     *
     * @param useAt the value for evt_vcode.use_at
     *
     * @mbggenerated
     */
    public void setUseAt(String useAt) {
        this.useAt = useAt == null ? null : useAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.fcode
     *
     * @return the value of evt_vcode.fcode
     *
     * @mbggenerated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.fcode
     *
     * @param fcode the value for evt_vcode.fcode
     *
     * @mbggenerated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.mobile
     *
     * @return the value of evt_vcode.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.mobile
     *
     * @param mobile the value for evt_vcode.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.create_at
     *
     * @return the value of evt_vcode.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.create_at
     *
     * @param createAt the value for evt_vcode.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evt_vcode.err_count
     *
     * @return the value of evt_vcode.err_count
     *
     * @mbggenerated
     */
    public Integer getErrCount() {
        return errCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evt_vcode.err_count
     *
     * @param errCount the value for evt_vcode.err_count
     *
     * @mbggenerated
     */
    public void setErrCount(Integer errCount) {
        this.errCount = errCount;
    }
}