package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.EnterpriseCore;
import yxinfo.core.service.ou.dao.model.EnterpriseCoreExample;

public interface EnterpriseCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    long countByExample(EnterpriseCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int deleteByExample(EnterpriseCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int insert(EnterpriseCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int insertSelective(EnterpriseCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    List<EnterpriseCore> selectByExample(EnterpriseCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    EnterpriseCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EnterpriseCore record, @Param("example") EnterpriseCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EnterpriseCore record, @Param("example") EnterpriseCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EnterpriseCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnterpriseCore record);
}