package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.SysAppTerminal;
import yxinfo.core.service.ou.dao.model.SysAppTerminalExample;

public interface SysAppTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int countByExample(SysAppTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int deleteByExample(SysAppTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int insert(SysAppTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int insertSelective(SysAppTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    List<SysAppTerminal> selectByExample(SysAppTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysAppTerminal record, @Param("example") SysAppTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_app_terminal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysAppTerminal record, @Param("example") SysAppTerminalExample example);
}