package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.SysIp;
import yxinfo.core.service.ou.dao.model.SysIpExample;

public interface SysIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int countByExample(SysIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int deleteByExample(SysIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int insert(SysIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int insertSelective(SysIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    List<SysIp> selectByExample(SysIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysIp record, @Param("example") SysIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ip
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysIp record, @Param("example") SysIpExample example);
}