package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.SysLoginRegionNum;
import yxinfo.core.service.ou.dao.model.SysLoginRegionNumExample;

public interface SysLoginRegionNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int countByExample(SysLoginRegionNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int deleteByExample(SysLoginRegionNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int insert(SysLoginRegionNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int insertSelective(SysLoginRegionNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    List<SysLoginRegionNum> selectByExample(SysLoginRegionNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysLoginRegionNum record, @Param("example") SysLoginRegionNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login_region_num
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysLoginRegionNum record, @Param("example") SysLoginRegionNumExample example);
}