package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.SysMemberMajor;
import yxinfo.core.service.ou.dao.model.SysMemberMajorExample;

public interface SysMemberMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    long countByExample(SysMemberMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int deleteByExample(SysMemberMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int insert(SysMemberMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int insertSelective(SysMemberMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    List<SysMemberMajor> selectByExample(SysMemberMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    SysMemberMajor selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysMemberMajor record, @Param("example") SysMemberMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysMemberMajor record, @Param("example") SysMemberMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMemberMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_major
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMemberMajor record);
}