package yxinfo.core.service.ou.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.ou.dao.model.SysOrgApp;
import yxinfo.core.service.ou.dao.model.SysOrgAppExample;

public interface SysOrgAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int countByExample(SysOrgAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int deleteByExample(SysOrgAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int insert(SysOrgApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int insertSelective(SysOrgApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    List<SysOrgApp> selectByExample(SysOrgAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOrgApp record, @Param("example") SysOrgAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_app
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOrgApp record, @Param("example") SysOrgAppExample example);
}