package yxinfo.yjh.dao.model;

import java.util.Date;

public class AdCore {
    private Integer id;

    //标题
    private String title;

    //图片路径
    private String pic;

    //位置（1首页左侧，2首页右侧）
    private Short position;

    //链接
    private String link;

    //状态（1停用，2启用）
    private Short fstatus;

    //创建时间
    private Date createAt;

    //上一次更新时间
    private Date updateAt;

    //发布人id，<FK>sys_member.id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.id
     *
     * @return the value of ad_core.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.id
     *
     * @param id the value for ad_core.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.title
     *
     * @return the value of ad_core.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.title
     *
     * @param title the value for ad_core.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.pic
     *
     * @return the value of ad_core.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.pic
     *
     * @param pic the value for ad_core.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.position
     *
     * @return the value of ad_core.position
     *
     * @mbg.generated
     */
    public Short getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.position
     *
     * @param position the value for ad_core.position
     *
     * @mbg.generated
     */
    public void setPosition(Short position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.link
     *
     * @return the value of ad_core.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.link
     *
     * @param link the value for ad_core.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.fstatus
     *
     * @return the value of ad_core.fstatus
     *
     * @mbg.generated
     */
    public Short getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.fstatus
     *
     * @param fstatus the value for ad_core.fstatus
     *
     * @mbg.generated
     */
    public void setFstatus(Short fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.create_at
     *
     * @return the value of ad_core.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.create_at
     *
     * @param createAt the value for ad_core.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.update_at
     *
     * @return the value of ad_core.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.update_at
     *
     * @param updateAt the value for ad_core.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_core.member_id
     *
     * @return the value of ad_core.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_core.member_id
     *
     * @param memberId the value for ad_core.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}