package yxinfo.yjh.dao.model;

import java.util.Date;

public class ArticleAnswer {
    private Integer id;

    //文章id，<FK>article_core.id
    private Integer articleId;

    //回答人id，<FK>sys_member.id
    private Integer memberId;

    //回答人姓名
    private String memberName;

    //回答人单位
    private String memberOrg;

    //创建时间
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.id
     *
     * @return the value of article_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.id
     *
     * @param id the value for article_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.article_id
     *
     * @return the value of article_answer.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.article_id
     *
     * @param articleId the value for article_answer.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.member_id
     *
     * @return the value of article_answer.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.member_id
     *
     * @param memberId the value for article_answer.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.member_name
     *
     * @return the value of article_answer.member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.member_name
     *
     * @param memberName the value for article_answer.member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.member_org
     *
     * @return the value of article_answer.member_org
     *
     * @mbg.generated
     */
    public String getMemberOrg() {
        return memberOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.member_org
     *
     * @param memberOrg the value for article_answer.member_org
     *
     * @mbg.generated
     */
    public void setMemberOrg(String memberOrg) {
        this.memberOrg = memberOrg == null ? null : memberOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_answer.create_at
     *
     * @return the value of article_answer.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_answer.create_at
     *
     * @param createAt the value for article_answer.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}