package yxinfo.yjh.dao.model;

import java.util.Date;

public class ArticleMoveHistory {
    private Integer id;

    //用户id
    private Integer memberId;

    //文章id，<Fk>article_core.id
    private Integer articleId;

    //文章类型（1文章，2提问）
    private Short ftype;

    //作者姓名
    private String authorName;

    //标题
    private String title;

    //源板块id
    private Integer fromBlockId;

    //目标板块id
    private Integer toBlockId;

    //创建时间
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.id
     *
     * @return the value of article_move_history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.id
     *
     * @param id the value for article_move_history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.member_id
     *
     * @return the value of article_move_history.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.member_id
     *
     * @param memberId the value for article_move_history.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.article_id
     *
     * @return the value of article_move_history.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.article_id
     *
     * @param articleId the value for article_move_history.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.ftype
     *
     * @return the value of article_move_history.ftype
     *
     * @mbg.generated
     */
    public Short getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.ftype
     *
     * @param ftype the value for article_move_history.ftype
     *
     * @mbg.generated
     */
    public void setFtype(Short ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.author_name
     *
     * @return the value of article_move_history.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.author_name
     *
     * @param authorName the value for article_move_history.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.title
     *
     * @return the value of article_move_history.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.title
     *
     * @param title the value for article_move_history.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.from_block_id
     *
     * @return the value of article_move_history.from_block_id
     *
     * @mbg.generated
     */
    public Integer getFromBlockId() {
        return fromBlockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.from_block_id
     *
     * @param fromBlockId the value for article_move_history.from_block_id
     *
     * @mbg.generated
     */
    public void setFromBlockId(Integer fromBlockId) {
        this.fromBlockId = fromBlockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.to_block_id
     *
     * @return the value of article_move_history.to_block_id
     *
     * @mbg.generated
     */
    public Integer getToBlockId() {
        return toBlockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.to_block_id
     *
     * @param toBlockId the value for article_move_history.to_block_id
     *
     * @mbg.generated
     */
    public void setToBlockId(Integer toBlockId) {
        this.toBlockId = toBlockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_move_history.create_at
     *
     * @return the value of article_move_history.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_move_history.create_at
     *
     * @param createAt the value for article_move_history.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}