package yxinfo.yjh.dao.model;

public class ArticleAttach {
    private Integer id;

    //文章id，<FK>article_core.id
    private Integer articleId;

    //附件名称
    private String fname;

    //附件路径
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_attach.id
     *
     * @return the value of article_attach.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_attach.id
     *
     * @param id the value for article_attach.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_attach.article_id
     *
     * @return the value of article_attach.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_attach.article_id
     *
     * @param articleId the value for article_attach.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_attach.fname
     *
     * @return the value of article_attach.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_attach.fname
     *
     * @param fname the value for article_attach.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_attach.path
     *
     * @return the value of article_attach.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_attach.path
     *
     * @param path the value for article_attach.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}