package yxinfo.yjh.dao.model;

public class BlockManagerKey {
    //板块id，<FK>block_core.id
    private Integer blockId;

    //用户id，<FK>sys_member.id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_manager.block_id
     *
     * @return the value of block_manager.block_id
     *
     * @mbg.generated
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_manager.block_id
     *
     * @param blockId the value for block_manager.block_id
     *
     * @mbg.generated
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_manager.member_id
     *
     * @return the value of block_manager.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_manager.member_id
     *
     * @param memberId the value for block_manager.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}