package yxinfo.yjh.dao.model;

public class FdlinkType {
    private Integer id;

    //网站类型
    private String ftype;

    //发布人id，<FK>sys_member.id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_type.id
     *
     * @return the value of fdlink_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_type.id
     *
     * @param id the value for fdlink_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_type.ftype
     *
     * @return the value of fdlink_type.ftype
     *
     * @mbg.generated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_type.ftype
     *
     * @param ftype the value for fdlink_type.ftype
     *
     * @mbg.generated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_type.member_id
     *
     * @return the value of fdlink_type.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_type.member_id
     *
     * @param memberId the value for fdlink_type.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}