package yxinfo.yjh.dao.model;

import java.util.Date;

public class FdlinkCore {
    private Integer id;

    //网站类型
    private String ftype;

    //网站名称
    private String fname;

    //链接
    private String link;

    //位置（1内页，2首页）
    private Short position;

    //创建时间
    private Date createAt;

    //上一次更新时间
    private Date updateAt;

    //发布人id，<FK>sys_member.id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.id
     *
     * @return the value of fdlink_core.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.id
     *
     * @param id the value for fdlink_core.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.ftype
     *
     * @return the value of fdlink_core.ftype
     *
     * @mbg.generated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.ftype
     *
     * @param ftype the value for fdlink_core.ftype
     *
     * @mbg.generated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.fname
     *
     * @return the value of fdlink_core.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.fname
     *
     * @param fname the value for fdlink_core.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.link
     *
     * @return the value of fdlink_core.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.link
     *
     * @param link the value for fdlink_core.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.position
     *
     * @return the value of fdlink_core.position
     *
     * @mbg.generated
     */
    public Short getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.position
     *
     * @param position the value for fdlink_core.position
     *
     * @mbg.generated
     */
    public void setPosition(Short position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.create_at
     *
     * @return the value of fdlink_core.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.create_at
     *
     * @param createAt the value for fdlink_core.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.update_at
     *
     * @return the value of fdlink_core.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.update_at
     *
     * @param updateAt the value for fdlink_core.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fdlink_core.member_id
     *
     * @return the value of fdlink_core.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fdlink_core.member_id
     *
     * @param memberId the value for fdlink_core.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}