package yxinfo.yjh.dao.model;

import java.util.Date;

public class MeetingCore {
    private Integer id;

    //发布人Id
    private Integer memberId;

    //会议名称
    private String fname;

    //参会人数
    private Integer attendPersonNum;

    //报名截至时间
    private Date signEndAt;

    //会议开始时间
    private Date startAt;

    //结束时间
    private Date endAt;

    //会议地点
    private String place;

    //咨询电话
    private String consoleMobile;

    //图片url
    private String picUrl;

    //会议状态(1、待发布 2、待进行 3、进行中 4、完成 5、取消)
    private Short fstatus;

    //报名状态（1、待报名 2、报名中 3、报名结束）
    private Short signStatus;

    //创建时间
    private Date createAt;

    //发布时间
    private Date publishAt;

    //取消原因
    private String cancelReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.id
     *
     * @return the value of meeting_core.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.id
     *
     * @param id the value for meeting_core.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.member_id
     *
     * @return the value of meeting_core.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.member_id
     *
     * @param memberId the value for meeting_core.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.fname
     *
     * @return the value of meeting_core.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.fname
     *
     * @param fname the value for meeting_core.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.attend_person_num
     *
     * @return the value of meeting_core.attend_person_num
     *
     * @mbg.generated
     */
    public Integer getAttendPersonNum() {
        return attendPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.attend_person_num
     *
     * @param attendPersonNum the value for meeting_core.attend_person_num
     *
     * @mbg.generated
     */
    public void setAttendPersonNum(Integer attendPersonNum) {
        this.attendPersonNum = attendPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.sign_end_at
     *
     * @return the value of meeting_core.sign_end_at
     *
     * @mbg.generated
     */
    public Date getSignEndAt() {
        return signEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.sign_end_at
     *
     * @param signEndAt the value for meeting_core.sign_end_at
     *
     * @mbg.generated
     */
    public void setSignEndAt(Date signEndAt) {
        this.signEndAt = signEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.start_at
     *
     * @return the value of meeting_core.start_at
     *
     * @mbg.generated
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.start_at
     *
     * @param startAt the value for meeting_core.start_at
     *
     * @mbg.generated
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.end_at
     *
     * @return the value of meeting_core.end_at
     *
     * @mbg.generated
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.end_at
     *
     * @param endAt the value for meeting_core.end_at
     *
     * @mbg.generated
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.place
     *
     * @return the value of meeting_core.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.place
     *
     * @param place the value for meeting_core.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.console_mobile
     *
     * @return the value of meeting_core.console_mobile
     *
     * @mbg.generated
     */
    public String getConsoleMobile() {
        return consoleMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.console_mobile
     *
     * @param consoleMobile the value for meeting_core.console_mobile
     *
     * @mbg.generated
     */
    public void setConsoleMobile(String consoleMobile) {
        this.consoleMobile = consoleMobile == null ? null : consoleMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.pic_url
     *
     * @return the value of meeting_core.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.pic_url
     *
     * @param picUrl the value for meeting_core.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.fstatus
     *
     * @return the value of meeting_core.fstatus
     *
     * @mbg.generated
     */
    public Short getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.fstatus
     *
     * @param fstatus the value for meeting_core.fstatus
     *
     * @mbg.generated
     */
    public void setFstatus(Short fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.sign_status
     *
     * @return the value of meeting_core.sign_status
     *
     * @mbg.generated
     */
    public Short getSignStatus() {
        return signStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.sign_status
     *
     * @param signStatus the value for meeting_core.sign_status
     *
     * @mbg.generated
     */
    public void setSignStatus(Short signStatus) {
        this.signStatus = signStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.create_at
     *
     * @return the value of meeting_core.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.create_at
     *
     * @param createAt the value for meeting_core.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.publish_at
     *
     * @return the value of meeting_core.publish_at
     *
     * @mbg.generated
     */
    public Date getPublishAt() {
        return publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.publish_at
     *
     * @param publishAt the value for meeting_core.publish_at
     *
     * @mbg.generated
     */
    public void setPublishAt(Date publishAt) {
        this.publishAt = publishAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_core.cancel_reason
     *
     * @return the value of meeting_core.cancel_reason
     *
     * @mbg.generated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_core.cancel_reason
     *
     * @param cancelReason the value for meeting_core.cancel_reason
     *
     * @mbg.generated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }
}