package yxinfo.yjh.dao.model;

import java.util.Date;

public class MeetingSign {
    private Integer id;

    //会议id
    private Integer meetingId;

    //报名人员Id
    private Integer memberId;

    //姓名
    private String memberName;

    //性别（1、男 2、女）
    private Short sex;

    //邮箱
    private String email;

    //单位名称
    private String org;

    //手机号
    private String mobile;

    //报名状态（1、报名成功 2、取消报名 ）
    private Short fstatus;

    //创建时间
    private Date createAt;

    //报名父Id
    private Integer pid;

    //签到状态（1、未签到 2、扫码签到 3、管理员代签）
    private Short signInType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.id
     *
     * @return the value of meeting_sign.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.id
     *
     * @param id the value for meeting_sign.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.meeting_id
     *
     * @return the value of meeting_sign.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.meeting_id
     *
     * @param meetingId the value for meeting_sign.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.member_id
     *
     * @return the value of meeting_sign.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.member_id
     *
     * @param memberId the value for meeting_sign.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.member_name
     *
     * @return the value of meeting_sign.member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.member_name
     *
     * @param memberName the value for meeting_sign.member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.sex
     *
     * @return the value of meeting_sign.sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.sex
     *
     * @param sex the value for meeting_sign.sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.email
     *
     * @return the value of meeting_sign.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.email
     *
     * @param email the value for meeting_sign.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.org
     *
     * @return the value of meeting_sign.org
     *
     * @mbg.generated
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.org
     *
     * @param org the value for meeting_sign.org
     *
     * @mbg.generated
     */
    public void setOrg(String org) {
        this.org = org == null ? null : org.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.mobile
     *
     * @return the value of meeting_sign.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.mobile
     *
     * @param mobile the value for meeting_sign.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.fstatus
     *
     * @return the value of meeting_sign.fstatus
     *
     * @mbg.generated
     */
    public Short getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.fstatus
     *
     * @param fstatus the value for meeting_sign.fstatus
     *
     * @mbg.generated
     */
    public void setFstatus(Short fstatus) {
        this.fstatus = fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.create_at
     *
     * @return the value of meeting_sign.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.create_at
     *
     * @param createAt the value for meeting_sign.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.pid
     *
     * @return the value of meeting_sign.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.pid
     *
     * @param pid the value for meeting_sign.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_sign.sign_in_type
     *
     * @return the value of meeting_sign.sign_in_type
     *
     * @mbg.generated
     */
    public Short getSignInType() {
        return signInType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_sign.sign_in_type
     *
     * @param signInType the value for meeting_sign.sign_in_type
     *
     * @mbg.generated
     */
    public void setSignInType(Short signInType) {
        this.signInType = signInType;
    }
}