package yxinfo.core.service.sms.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.core.service.sms.dao.model.EvtSmsRecord;
import yxinfo.core.service.sms.dao.model.EvtSmsRecordExample;

public interface EvtSmsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int countByExample(EvtSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int deleteByExample(EvtSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int insert(EvtSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int insertSelective(EvtSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    List<EvtSmsRecord> selectByExample(EvtSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    EvtSmsRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EvtSmsRecord record, @Param("example") EvtSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EvtSmsRecord record, @Param("example") EvtSmsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvtSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evt_sms_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvtSmsRecord record);
}