package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.AdCore;
import yxinfo.yjh.dao.model.AdCoreExample;

public interface AdCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    long countByExample(AdCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int deleteByExample(AdCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int insert(AdCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int insertSelective(AdCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    List<AdCore> selectByExample(AdCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    AdCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdCore record, @Param("example") AdCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdCore record, @Param("example") AdCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdCore record);
}