package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.ApproveCore;
import yxinfo.yjh.dao.model.ApproveCoreExample;

public interface ApproveCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    long countByExample(ApproveCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int deleteByExample(ApproveCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int insert(ApproveCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int insertSelective(ApproveCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    List<ApproveCore> selectByExample(ApproveCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    ApproveCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApproveCore record, @Param("example") ApproveCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApproveCore record, @Param("example") ApproveCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApproveCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApproveCore record);
}