package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.ArticleCore;
import yxinfo.yjh.dao.model.ArticleCoreExample;

public interface ArticleCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    long countByExample(ArticleCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int insert(ArticleCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int insertSelective(ArticleCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    List<ArticleCore> selectByExample(ArticleCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    ArticleCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleCore record, @Param("example") ArticleCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleCore record, @Param("example") ArticleCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleCore record);
}