package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.ArticleAnswer;
import yxinfo.yjh.dao.model.ArticleAnswerExample;

public interface ArticleAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    long countByExample(ArticleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int insert(ArticleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int insertSelective(ArticleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    List<ArticleAnswer> selectByExample(ArticleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    ArticleAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleAnswer record, @Param("example") ArticleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleAnswer record, @Param("example") ArticleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleAnswer record);
}