package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.ArticleAnswerContext;
import yxinfo.yjh.dao.model.ArticleAnswerContextExample;

public interface ArticleAnswerContextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    long countByExample(ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer articleAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int insert(ArticleAnswerContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int insertSelective(ArticleAnswerContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    List<ArticleAnswerContext> selectByExampleWithBLOBs(ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    List<ArticleAnswerContext> selectByExample(ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    ArticleAnswerContext selectByPrimaryKey(Integer articleAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleAnswerContext record, @Param("example") ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleAnswerContext record, @Param("example") ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleAnswerContext record, @Param("example") ArticleAnswerContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleAnswerContext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_answer_context
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ArticleAnswerContext record);
}