package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.ArticleAttach;
import yxinfo.yjh.dao.model.ArticleAttachExample;

public interface ArticleAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    long countByExample(ArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int insert(ArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int insertSelective(ArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    List<ArticleAttach> selectByExample(ArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    ArticleAttach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleAttach record, @Param("example") ArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleAttach record, @Param("example") ArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleAttach record);
}