package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.BlockCore;
import yxinfo.yjh.dao.model.BlockCoreExample;

public interface BlockCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    long countByExample(BlockCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int deleteByExample(BlockCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int insert(BlockCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int insertSelective(BlockCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    List<BlockCore> selectByExample(BlockCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    BlockCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlockCore record, @Param("example") BlockCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlockCore record, @Param("example") BlockCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlockCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlockCore record);
}