package yxinfo.yjh.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.yjh.dao.model.FdlinkType;
import yxinfo.yjh.dao.model.FdlinkTypeExample;

public interface FdlinkTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    long countByExample(FdlinkTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int deleteByExample(FdlinkTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int insert(FdlinkType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int insertSelective(FdlinkType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    List<FdlinkType> selectByExample(FdlinkTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    FdlinkType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FdlinkType record, @Param("example") FdlinkTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FdlinkType record, @Param("example") FdlinkTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FdlinkType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fdlink_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FdlinkType record);
}